version: '3'
services:

  # webserver
  web:
    image: "lier/web:latest"
    expose:
     - 3001
    volumes:
     - ../app:/entrypoint
    working_dir: /entrypoint
    # command: npm start
    command: nodemon app.js
  
  # wordpress
  wordpress:
    image: wordpress
    ports:
      - 3002:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  # key storage
  redis:
    image: "redis"
    volumes:
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
  
  # reverse-proxy
  nginx:
    image: "lier/nginx:latest"
    links:
      - web
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx
