version: '3'

volumes:
  wordpress_storage:
    external: false
  mariadb_storage:
    external: false
  redis_storage:
    external: false
  image_storage:
    external: false

services:

  web:
    build: build/web
    image: lier/web:latest
    volumes:
      - ../app:/entrypoint
      - ../config/app-config.js:/entrypoint/app-config.js:ro
      - image_storage:/uploads
    links: 
      - redis
    command: sh start-server.sh
      
  wordpress:
    build: build/wordpress
    image: lier/wordpress:latest
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - wordpress_storage:/var/www/html/wp-content/uploads
  
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb_storage:/var/lib/mysql

  redis:
    build: build/redis
    image: lier/redis:latest
    volumes:
      - ../config/redis.conf:/tmp/redis.conf:ro
      - redis_storage:/redis_storage
    command: redis-server /tmp/redis.conf
  
  nginx:
    build: build/nginx
    image: lier/nginx:latest
    links:
      - web
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx

